### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by felipehuerta17** [CataPino/rfb-model#2]
Short time development goals

- [ ] Include Forcheimer terms in the fvOptions of porous blockage.
- [ ] Modify Navier Stokes equation to convert it to Brickman Equation.
- [ ] Add species for scalar transport.

**Comment by felipehuerta17** [comment]
<img src="https://render.githubusercontent.com/render/math?math=a^{2} %2B b^{2} = c^{2}">
